import os
import json
import tkinter as tk
from tkinter import ttk, messagebox, filedialog

from sidebar import Sidebar
from canvas import VisualCanvas
from codegen import CodeGenerator
from runner import Runner, LINKER_LD
from blocks import load_blocks
from nodes import Node

BUILD_SH_C = """#!/bin/bash
set -e
echo "[1/3] Compiling kernel.c..."
gcc -m32 -ffreestanding -fno-pie -nostdlib -fno-stack-protector -c kernel.c -o kernel.o
echo "[2/3] Linking..."
ld -m elf_i386 -T linker.ld -z noexecstack --no-warn-rwx-segments -o kernel.bin kernel.o
echo "[3/3] Done. Run with ./run.sh or ./iso.sh"
rm -f kernel.o
"""

BUILD_SH_ASM = """#!/bin/bash
set -e
echo "[1/3] Assembling kernel.asm..."
nasm -f elf32 kernel.asm -o kernel.o
echo "[2/3] Linking..."
ld -m elf_i386 -T linker.ld -z noexecstack -o kernel.bin kernel.o
echo "[3/3] Done. Run with ./run.sh or ./iso.sh"
rm -f kernel.o
"""

ISO_SH = """#!/bin/bash
set -e
echo "Building bootable ISO..."
mkdir -p isodir/boot/grub
cp kernel.bin isodir/boot/
echo 'menuentry "MyOS" { multiboot /boot/kernel.bin }' > isodir/boot/grub/grub.cfg
grub-mkrescue -o myos.iso isodir
echo "Success! Run with: qemu-system-i386 -cdrom myos.iso"
"""

RUN_SH = """#!/bin/bash
qemu-system-i386 -kernel kernel.bin -display gtk
"""

EXPORT_README = """# My OS Project
This folder contains a complete bootable Operating System generated by OSDev Visual Studio.

## Files
- `kernel.c` or `kernel.asm`: The OS source code.
- `linker.ld`: The linker script that tells the compiler where to put the Multiboot header and code.
- `build.sh`: Compiles the source code into `kernel.bin`.
- `run.sh`: Launches `kernel.bin` in QEMU directly.
- `iso.sh`: Packs `kernel.bin` into a bootable `.iso` file (requires `grub-mkrescue`).

## How to Run
1. Open a terminal in this folder.
2. Make scripts executable: `chmod +x *.sh`
3. Build the OS: `./build.sh`
4. Run the OS: `./run.sh`

## Dependencies
You need `gcc`, `ld`, `nasm`, and `qemu-system-i386` installed.
On Ubuntu/Debian: `sudo apt install build-essential nasm qemu-system-x86 grub-pc-bin xorriso`
"""

class OSDevStudio:
    def __init__(self, root):
        self.root = root
        self.root.title("OSDev Visual Studio")
        self.root.geometry("1280x780")
        self.root.minsize(960, 620)
        
        self.blocks = load_blocks()
        self.code_mode = tk.StringVar(value="c")
        self.status_var = tk.StringVar(value="Ready. Middle-click drag to pan. Left-click drag to select. Alt+drag to snap to grid.")
        self.runner = Runner(self.status_var)
        
        toolbar = tk.Frame(root, bg="#222222", height=46)
        toolbar.pack(side=tk.TOP, fill=tk.X)
        
        btn_container = tk.Frame(toolbar, bg="#222222")
        btn_container.pack(expand=True)
        
        def mk_btn(text, cmd):
            tk.Button(btn_container, text=text, command=cmd, bg="#4a4a4a", fg="white", 
                      font=("Helvetica", 10, "bold"), relief=tk.FLAT, padx=14, pady=8, 
                      cursor="hand2").pack(side=tk.LEFT, padx=5, pady=6)
            
        mk_btn("Run QEMU", self.run_code)
        mk_btn("Export OS", self.export_code)
        mk_btn("Toggle Code Preview", self.toggle_code)
        mk_btn("Save Schematic", self.save_schematic)
        mk_btn("Load Schematic", self.load_schematic)
        mk_btn("Clear", self.clear_all)
        mk_btn("Manual", self.show_manual)
        
        self.paned = tk.PanedWindow(root, orient=tk.HORIZONTAL, sashwidth=4, bg="#333333")
        self.paned.pack(fill=tk.BOTH, expand=True)
        
        self.sidebar = Sidebar(self.paned, self.blocks, None)
        self.paned.add(self.sidebar.frame, minsize=200)
        
        self.canvas = VisualCanvas(self.paned, self.blocks, on_change_callback=self.on_graph_change, on_select_callback=self.on_node_select)
        self.canvas.selecting = False
        self.sidebar.canvas = self.canvas
        self.paned.add(self.canvas.frame, minsize=420)
        
        self.code_frame = tk.Frame(self.paned, bg="#1e1e1e", width=520)
        
        top = tk.Frame(self.code_frame, bg="#222222")
        top.pack(fill=tk.X)
        tk.Label(top, text="Generated Code", fg="#e0e0e0", bg="#222222", font=("Helvetica", 11, "bold"), padx=10, pady=8).pack(side=tk.LEFT)
        tk.Radiobutton(top, text="C Kernel", variable=self.code_mode, value="c", command=self.update_code, bg="#222222", fg="#e0e0e0", selectcolor="#2e2e2e", activebackground="#222222", activeforeground="#e0e0e0").pack(side=tk.LEFT, padx=4)
        tk.Radiobutton(top, text="NASM", variable=self.code_mode, value="asm", command=self.update_code, bg="#222222", fg="#e0e0e0", selectcolor="#2e2e2e", activebackground="#222222", activeforeground="#e0e0e0").pack(side=tk.LEFT, padx=4)
        
        text_frame = tk.Frame(self.code_frame, bg="#1e1e1e")
        text_frame.pack(fill=tk.BOTH, expand=True)
        self.code_text = tk.Text(text_frame, bg="#1e1e1e", fg="#d4d4d4", font=("Consolas", 10), wrap=tk.NONE, insertbackground="white", relief=tk.FLAT, padx=10, pady=8, undo=True)
        sy = tk.Scrollbar(text_frame, orient=tk.VERTICAL, command=self.code_text.yview, bg="#222222", troughcolor="#1e1e1e")
        sx = tk.Scrollbar(text_frame, orient=tk.HORIZONTAL, command=self.code_text.xview, bg="#222222", troughcolor="#1e1e1e")
        self.code_text.config(yscrollcommand=sy.set, xscrollcommand=sx.set)
        sy.pack(side=tk.RIGHT, fill=tk.Y)
        sx.pack(side=tk.BOTTOM, fill=tk.X)
        self.code_text.pack(fill=tk.BOTH, expand=True)
        self.code_text.bind("<Motion>", self.on_code_hover)
        
        self.code_panel_visible = False
        
        status = tk.Label(root, textvariable=self.status_var, bg="#222222", fg="#888888", anchor=tk.W, font=("Helvetica", 9))
        status.pack(side=tk.BOTTOM, fill=tk.X)
        
        self.load_default_schematic()
        self.update_code()
        
    def toggle_code(self):
        if self.code_panel_visible:
            self.paned.forget(self.code_frame)
            self.code_panel_visible = False
        else:
            self.paned.add(self.code_frame, minsize=320)
            self.code_panel_visible = True
            
    def on_graph_change(self):
        self.update_code()
        
    def on_node_select(self):
        self.highlight_active_node()
        
    def on_code_hover(self, event):
        index = self.code_text.index(f"@{event.x},{event.y}")
        tags = self.code_text.tag_names(index)
        for tag in tags:
            if tag.startswith("node_"):
                nid = int(tag.split("_")[1])
                self.canvas.set_hover_node(nid)
                return
        self.canvas.set_hover_node(None)
        
    def update_code(self):
        gen = CodeGenerator(self.canvas.nodes, self.canvas.connections, self.blocks)
        code_lines, tag_lines = gen.generate(self.code_mode.get())
        self.code_text.config(state="normal")
        self.code_text.delete("1.0", tk.END)
        for i, (line, nid) in enumerate(zip(code_lines, tag_lines)):
            self.code_text.insert("end", line + "\n")
            if nid is not None:
                self.code_text.tag_add(f"node_{nid}", f"{i+1}.0", f"{i+2}.0")
        self.code_text.config(state="disabled")
        self.highlight_active_node()
        
    def highlight_active_node(self):
        for tag in self.code_text.tag_names():
            if tag.startswith("node_"):
                self.code_text.tag_config(tag, background="")
        if self.canvas.selected_node:
            nid = self.canvas.selected_node.id
            self.code_text.tag_config(f"node_{nid}", background="#3a3000")
            
    def run_code(self):
        self.update_code()
        code = self.code_text.get("1.0", "end-1c")
        self.runner.run(code, self.code_mode.get())
        
    def export_code(self):
        self.update_code()
        if self.code_mode.get() == "c":
            ext, ftypes, initial = ".c", [("C source", "*.c")], "kernel.c"
        else:
            ext, ftypes, initial = ".asm", [("NASM asm", "*.asm")], "kernel.asm"
            
        path = filedialog.asksaveasfilename(defaultextension=ext, filetypes=ftypes, initialfile=initial)
        if not path: return
        
        dirname = os.path.dirname(os.path.abspath(path))
        with open(path, "w") as f: f.write(self.code_text.get("1.0", tk.END))
        with open(os.path.join(dirname, "linker.ld"), "w") as f: f.write(LINKER_LD)
        
        build_sh = BUILD_SH_C if self.code_mode.get() == "c" else BUILD_SH_ASM
        build_path = os.path.join(dirname, "build.sh")
        with open(build_path, "w") as f: f.write(build_sh)
        os.chmod(build_path, 0o755)
        
        run_path = os.path.join(dirname, "run.sh")
        with open(run_path, "w") as f: f.write(RUN_SH)
        os.chmod(run_path, 0o755)
        
        iso_path = os.path.join(dirname, "iso.sh")
        with open(iso_path, "w") as f: f.write(ISO_SH)
        os.chmod(iso_path, 0o755)
        
        readme_path = os.path.join(dirname, "README.md")
        with open(readme_path, "w") as f: f.write(EXPORT_README)
        
        self.status_var.set(f"Exported complete OS to: {dirname}")
        messagebox.showinfo("Exported", f"Complete OS exported to:\n{dirname}\n\nTo run:\n1. cd {dirname}\n2. ./build.sh\n3. ./run.sh")
        
    def save_schematic(self):
        path = filedialog.asksaveasfilename(defaultextension=".schematic", filetypes=[("Schematic", "*.schematic")], initialfile="my_os.schematic")
        if not path: return
        
        data = {"nodes": [], "connections": []}
        for n in self.canvas.nodes:
            # Added "w" and "h" so custom block sizes are saved
            data["nodes"].append({"id": n.id, "type": n.type, "x": n.x, "y": n.y, "w": n.w, "h": n.h, "properties": n.properties})
        for c in self.canvas.connections:
            data["connections"].append(c)
            
        with open(path, "w") as f:
            json.dump(data, f, indent=4)
        self.status_var.set(f"Saved schematic to {path}")
        
    def load_schematic(self):
        path = filedialog.askopenfilename(filetypes=[("Schematic", "*.schematic")])
        if not path: return
        
        with open(path, "r") as f:
            data = json.load(f)
            
        self.canvas.nodes.clear()
        self.canvas.connections.clear()
        Node._next_id = 1
        
        for n_data in data["nodes"]:
            n = Node(n_data["type"], n_data["x"], n_data["y"])
            n.id = n_data["id"]
            if n.id >= Node._next_id: Node._next_id = n.id + 1
            n.properties = n_data["properties"]
            # Restore custom dimensions if they exist
            if "w" in n_data: n.w = n_data["w"]
            if "h" in n_data: n.h = n_data["h"]
            # Recalculate comment size just in case the font changed
            if n.type == "comment":
                self.canvas.update_comment_size(n)
            self.canvas.nodes.append(n)
            
        for c_data in data["connections"]:
            self.canvas.connections.append(c_data)
            
        self.canvas.redraw()
        self.update_code()
        self.status_var.set(f"Loaded schematic from {path}")
        
    def clear_all(self):
        if messagebox.askyesno("Clear", "Clear all blocks?"):
            self.canvas.nodes.clear()
            self.canvas.connections.clear()
            self.canvas.redraw()
            self.update_code()
            
    def show_manual(self):
        try:
            with open("manual.json", "r") as f:
                manual = json.load(f)
        except:
            messagebox.showerror("Error", "manual.json not found!")
            return
            
        win = tk.Toplevel(self.root)
        win.title("OSDev Visual Studio - Manual")
        win.geometry("800x500")
        win.configure(bg="#1e1e1e")
        
        paned = tk.PanedWindow(win, orient=tk.HORIZONTAL, bg="#333333", sashwidth=4)
        paned.pack(fill="both", expand=True, padx=10, pady=10)
        
        list_frame = tk.Frame(paned, bg="#1e1e1e", width=200)
        paned.add(list_frame, minsize=150)
        
        tk.Label(list_frame, text="Blocks", fg="#e0e0e0", bg="#1e1e1e", font=("Helvetica", 12, "bold")).pack(pady=5)
        
        listbox = tk.Listbox(list_frame, bg="#222222", fg="#e0e0e0", selectbackground="#4a4a4a", selectforeground="white", font=("Helvetica", 10), activestyle="none", relief=tk.FLAT, highlightthickness=0)
        listbox.pack(fill="both", expand=True)
        
        desc_frame = tk.Frame(paned, bg="#1e1e1e")
        paned.add(desc_frame, minsize=400)
        
        title_lbl = tk.Label(desc_frame, text="Select a block", fg="#e0e0e0", bg="#1e1e1e", font=("Helvetica", 16, "bold"))
        title_lbl.pack(anchor="w", pady=(10, 5), padx=10)
        
        cat_lbl = tk.Label(desc_frame, text="", fg="#888888", bg="#1e1e1e", font=("Helvetica", 10, "italic"))
        cat_lbl.pack(anchor="w", padx=10)
        
        desc_text = tk.Text(desc_frame, bg="#1e1e1e", fg="#d4d4d4", font=("Helvetica", 11), wrap="word", relief=tk.FLAT, padx=10, pady=10)
        desc_text.pack(fill="both", expand=True)
        desc_text.config(state="disabled")
        
        blocks_info = {}
        for cat in manual["categories"]:
            for block in cat["blocks"]:
                blocks_info[block["name"]] = (cat["name"], block["description"], cat["color"])
                listbox.insert(tk.END, block["name"])
                listbox.itemconfig(listbox.size() - 1, {"fg": cat["color"]})
                
        def on_select(evt):
            if listbox.curselection():
                idx = listbox.curselection()[0]
                name = listbox.get(idx)
                cat, desc, color = blocks_info[name]
                title_lbl.config(text=name, fg=color)
                cat_lbl.config(text=f"Category: {cat}", fg="#888888")
                desc_text.config(state="normal")
                desc_text.delete("1.0", tk.END)
                desc_text.insert("1.0", desc)
                desc_text.config(state="disabled")
                
        listbox.bind("<<ListboxSelect>>", on_select)
        
    def load_default_schematic(self):
        path = "default.schematic"
        if not os.path.exists(path):
            self.canvas.nodes.clear()
            self.canvas.connections.clear()
            self.canvas.add_node("boot", 100, 100)
            return
            
        with open(path, "r") as f:
            data = json.load(f)
            
        self.canvas.nodes.clear()
        self.canvas.connections.clear()
        Node._next_id = 1
        
        for n_data in data["nodes"]:
            n = Node(n_data["type"], n_data["x"], n_data["y"])
            n.id = n_data["id"]
            if n.id >= Node._next_id: Node._next_id = n.id + 1
            n.properties = n_data["properties"]
            # Applied your fix here so it scales perfectly on startup too!
            if "w" in n_data: n.w = n_data["w"]
            if "h" in n_data: n.h = n_data["h"]
            if n.type == "comment":
                self.canvas.update_comment_size(n)
            self.canvas.nodes.append(n)
            
        for c_data in data["connections"]:
            self.canvas.connections.append(c_data)
            
        self.canvas.redraw()

if __name__ == "__main__":
    root = tk.Tk()
    app = OSDevStudio(root)
    root.mainloop()